[lib]
proc-macro = true

[package]
name = "inline_proc_macros"
version = "0.1.0"
authors = ["Daniel Henry-Mantilla <daniel.henry.mantilla@gmail.com>"]
edition = "2018"

[dependencies]
tempdir = "=0.3.6"
base64 = "0.12.3"
watt = { git = "https://github.com/mystor/watt", branch = "wasm_string" }

[workspace]
members = ["build"]
